# Database
spring.datasource.url=jdbc:mysql://localhost:3306/tenant_based_edu_portal
spring.datasource.username=your_username
spring.datasource.password=your_password

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# JWT
jwt.secret=YOUR_BASE64_SECRET_KEY
jwt.expiration=86400000

# Super Admin
app.super-admin.email=superadmin@example.com
app.super-admin.password=ChangeMe123!