# Database
spring.datasource.url=jdbc:postgresql://localhost:5432/tenant_based_edu_portal
spring.datasource.username=your_username
spring.datasource.password=your_password

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# JWT
jwt.secret=YOUR_BASE64_SECRET_KEY
jwt.expiration=86400000

# Super Admin
app.super-admin.email=SUPER_ADMIN_EMAIL
app.super-admin.password=SUPER_ADMIN_PASSWORD

# EMAIL CONFIG
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=YOUR_EMAIL@gmail.com
spring.mail.password=YOUR_GMAIL_APP_PASSWORD

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true